### ISSUE TITLE
Incompatibility between lineno and \directlua

### ISSUE THREAD

**Issue by fpantigny** [latex-lineno/lineno#11]
When I try to compile the following MWE with LuaLaTeX, I have an error : `invalid escape sequence near '"\p'`

```
\documentclass{article}
\usepackage{lineno}

\begin{document}

\directlua{tex.print("\\LaTeX")}

\end{document}
```

When `lineno` is not loaded, I have the expected output.

I think that the reason is that `\\` is not protected when `lineno` has been loaded. If I add `\robustify\\` (with `\robustify` of `etoolbox`) it works.

**Comment by kwwette** [comment]
I don't think this is specific to `lineno`.

`\directlua` [expands its argument in TeX before feeding to Lua](https://www.overleaf.com/learn/latex/Articles/An_Introduction_to_LuaTeX_(Part_2)%3A_Understanding_%5Cdirectlua#More_formal_description_of_\directlua), so the `\\` is being interpreted as a TeX command, rather than an escaped `\`. Any package that modifies `\\` in any way (including `lineno`) is probably going to break this usage.

Instead you probably want to write `\directlua{tex.print("\textbackslash LaTeX")}` to get a literal backslash passed to Lua.
