### ISSUE TITLE
linenomath environment doesn't work fully with breqn displays

### ISSUE THREAD

**Issue by FrankMittelbach** [latex-lineno/lineno#4]
The lineno package, does now automatically supports amsmath environments, but of course there are others. For that there is the `linenomath` environment but in case of `dmath` from breqn that doesn't fully work: the last line in front of the display is not getting a line number. It can be fixed by ading a `\par`but I doubt that this is the right solution.

MWE:
```
\documentclass{article}

\usepackage{breqn}
\usepackage{lineno,kantlipsum}
\begin{document}

\linenumbers

\kant*[1][1]
Hello world
\begin{dmath}
x+y+z+t+x+y+z+t+x+y+z+t+x+y+z+t+
x+y+z+t+x+y+z+t+x+y+z+t+x+y+z+t+
x+y+z+t+x+y+z+t+x+y+z+t+x+y+z+t+
x+y+z+t+x+y+z+t+x+y+z+t+x+y+z+t+
x
\end{dmath}
\kant*[2] Another breqn test:
\begin{linenomath}
\begin{dmath}
x+y+z+t+x+y+z+t+x+y+z+t+x+y+z+t+
x+y+z+t+x+y+z+t+x+y+z+t+x+y+z+t+
x+y+z+t+x+y+z+t+x+y+z+t+x+y+z+t+
x+y+z+t+x+y+z+t+x+y+z+t+x+y+z+t+
x
\end{dmath}
\end{linenomath}
\kant[4][1]

\AddToHook{env/dmath/before}{\par\begin{linenomath}}       % this makes it work
\AddToHook{env/dmath/after}{\end{linenomath}}              % automatically

\kant*[2] Another breqn test:
\begin{dmath}
x+y+z+t+x+y+z+t+x+y+z+t+x+y+z+t+
x+y+z+t+x+y+z+t+x+y+z+t+x+y+z+t+
x+y+z+t+x+y+z+t+x+y+z+t+x+y+z+t+
x+y+z+t+x+y+z+t+x+y+z+t+x+y+z+t+
x
\end{dmath}
\kant[4][1]

\end{document} 
```

**Comment by kwwette** [comment]
I had a quick look at this, but ran into quite a few issues:
- It appears `dmath` cannot be patched with `etoolbox`, which limits any solution to using `\AddToHook`, which is only available in relatively new LaTeX releases (since October 2020) and most operating systems are slow to update their LaTeX releases (including my laptop). This means that any fix is going to have a limited user base for some time.
- Even once I'd locally installed a new enough TeXLive distribution to be able to test the `\AddToHook` MWE, I couldn't get the simple `\par` fix to work, instead I'd get pages of text disappearing for some reason.
- Not only is the last line before the `dmath` display missing a linenumber, but a multi-line `dmath` display only added a line number to the last math line. And with `dmath*` environments, all line numbers on the preceding paragraph were missing. So the simple `\par` fix wouldn't be enough, even if I could get it working.

Given all that and my limited time I'm afraid this is a wont-fix for now.

**Comment by FrankMittelbach** [comment]
@kwwette understood, and I'm not surprised. I mainly reported it so that it is documented as an issue (and possibly an issue one has to live with it for the forseeable future. breqn is doing so much surgery to the standard processing that it is surprising that it more or less works at all.

**Comment by kwwette** [comment]
Closing this issue as this is unlikely to be fixed. The issue tracker will still document the problem for posterity.
